### PR TITLE
Facial recognition

### PR DESCRIPTION
**Pull request by rachelwebb**
For some reason, the facial recognition lab in the repository is an old draft. This is the up-to-date copy.

I realize it may not be possible to merge this commit because it is pre-git-restructuring. Just let me know what to do.

### CODE REVIEW

**Comment by ayr0** [comment]
git mv will move files in the repository.  You can read the help at git help mv.
Simply move the lab from its current location to a folder under Labs.  Make the new folder name specific.  Eigenfaces would be my first thought.

**Comment by rachelwebb** [comment]
I tried to do what you suggested . . . let me know if I did it right.

**Comment by aamcbee** [comment]
You moved them just right, but the tex file itself is calling applications. Perhaps you should try changing that first to make sure it has the right call.

**Comment by aamcbee** [comment]
This pull request was merged via the recent pull request RWebbFacialRecognition

**Pull request closed without merging**
